import { createFileRoute } from "@tanstack/react-router";
import { ListChecks } from "lucide-react";
import { useState } from "react";
import { AiOutput } from "@/components/AiOutput";
import { AppShell } from "@/components/AppShell";
import { ChoiceGroup, Field, GenerateButton, ToolGrid, ToolIntro } from "@/components/ToolLayout";
import { useAssistant } from "@/hooks/useAssistant";

const title = "AI Task Planner — AetherFlow AI Assistant";
const description =
  "Prioritise your workload and get a realistic time-blocked schedule generated by AI in seconds.";

export const Route = createFileRoute("/tasks")({
  head: () => ({
    meta: [
      { title },
      { name: "description", content: description },
      { property: "og:title", content: title },
      { property: "og:description", content: description },
    ],
  }),
  component: TasksPage,
});

function TasksPage() {
  const { content, error, loading, generate } = useAssistant("tasks");
  const [tasks, setTasks] = useState("");
  const [horizon, setHorizon] = useState("Today");
  const [capacity, setCapacity] = useState("6 hours");

  return (
    <AppShell title="AI Task Planner">
      <ToolGrid
        input={
          <form
            onSubmit={(e) => {
              e.preventDefault();
              if (tasks.trim()) void generate(tasks, { horizon, capacity });
            }}
            className="space-y-5"
          >
            <ToolIntro
              icon={ListChecks}
              title="Priority Planner"
              subtitle="Rank, schedule and protect your focus time"
            />
            <Field label="Planning horizon">
              <ChoiceGroup
                options={["Today", "Tomorrow", "This week"]}
                value={horizon}
                onChange={setHorizon}
              />
            </Field>
            <Field label="Available focus capacity">
              <ChoiceGroup
                options={["3 hours", "6 hours", "8 hours"]}
                value={capacity}
                onChange={setCapacity}
              />
            </Field>
            <Field label="Your tasks">
              <textarea
                value={tasks}
                onChange={(e) => setTasks(e.target.value)}
                rows={10}
                placeholder={"Finalise Q3 report (due 5pm)\nPrep client demo\nReview design system PR\n1:1 with Sarah"}
                className="w-full resize-none rounded-xl border border-border bg-background p-4 text-sm outline-none transition-all focus:ring-2 focus:ring-ring/25"
              />
            </Field>
            <GenerateButton loading={loading} label="Build My Plan" disabled={!tasks.trim()} />
          </form>
        }
        output={
          <AiOutput
            label="Prioritised plan"
            content={content}
            loading={loading}
            error={error}
            emptyHint="List everything on your plate — the planner ranks it and blocks out your day."
          />
        }
      />
    </AppShell>
  );
}
